
package cn.com.webxml;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-12-20T17:09:05.331+08:00
 * Generated source version: 3.4.1
 *
 */

public class MobileCodeWSSoap_MobileCodeWSSoap_Server{

    protected MobileCodeWSSoap_MobileCodeWSSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MobileCodeWSSoapImpl();
        String address = "http://www.huey.com:8888/WebServices/MobileCodeWS.asmx";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new MobileCodeWSSoap_MobileCodeWSSoap_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
