
package cn.com.webxml;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-12-20T17:09:05.428+08:00
 * Generated source version: 3.4.1
 *
 */

public class MobileCodeWSHttpPost_MobileCodeWSHttpPost_Server{

    protected MobileCodeWSHttpPost_MobileCodeWSHttpPost_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MobileCodeWSHttpPostImpl();
        String address = "http://ws.webxml.com.cn/WebServices/MobileCodeWS.asmx";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new MobileCodeWSHttpPost_MobileCodeWSHttpPost_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
