spring:
  datasource:
    url: jdbc:mysql://localhost/huey_learning
    username: root
    password: huey2672
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      validation-query: SELECT 1
      db-type: mysql